site_name: Raid Documentation
nav:
  - Home: 'index.md'
  - Reference:
      - Utility Functions: 'reference/utility-functions.md'
      - Classes:
          - String: 'reference/classes/string.md'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
theme:
  name: material
  palette:
    primary: light green
    accent: green
  icon:
    logo: material/buffer

docs_dir: 'docs_src'
site_dir: 'docs'